version: '3'
services:
  elasticsearch:
    restart: always
#    image: elasticsearch:7.9.1
    build: ./docker/es
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node" #以单一节点模式启动
    ports:
      - 9201:9200
  app:
    restart: always
    build: ./docker/java
    container_name: app
    ports:
      - 8082:8080
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    external_links:
      - elasticsearch
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh"
    entrypoint: "./wait-for-it.sh elasticsearch:9200 -t 10  -- java -jar app.jar"
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200